const Manager = require("./lib/Manager");
const Engineer = require("./lib/Engineer");
const Intern = require("./lib/Intern");
const inquirer = require("inquirer");
const path = require("path");
const fs = require("fs");


//is this the first time using path as a module?
const OUTPUT_DIR = path.resolve(__dirname, "output");
const outputPath = path.join(OUTPUT_DIR, "team.html");

const render = require("./src/page-template.js");


// TODO: Write Code to gather information about the development team members, and render the HTML file. NOTE the HTML is already laid out in file ./src/page-template.js

//Rough prompt layout using Inquirer, wrapped in a function
function promptUser() {
    return inquirer
      .prompt([
        {
            type: 'input',
            name: 'name',
            message: 'Enter employee name',
        },
    
        {
            type: 'list',
            name: 'role',
            message: 'Choose employee role',
            choices: ['Manager', 'Engineer', 'Intern'],
            //is there a point in making a choice here if there are now three subclasses?
        },
       
    
        {
            type: 'input',
            name: 'email',
            message: 'Please enter your email address',
        },

        {
            type: 'input',
            name: 'github',
            message: 'Please enter your GitHub username',
            //for Engineer subclass only
        },

        {
            type: 'input',
            name: 'offNum',
            message: 'Please enter your office number',
            //for Manager subclass only
        },

        {
            type: 'input',
            name: 'github',
            message: 'Please enter your School name',
            //for Intern subclass only
        },
      ]);
    }

    // remember rest of code after above, calling promptUser function!


    // Is ID autogenerated for each person? Does it have to correspond to the screengrab i.e. Managers are assigned first numbers and interns later numbers with Engineers in the middle?

    //Code to render the html 
