// TODO: Write code to define and export the Employee class

// Make sure there is no first name/last name issue, there is just a single name accounted for here

// is ID autogenerated? 

//watch for the capitalization (or not)

class Employee {
    constructor (id, name, email) { 
        this.id = id;
        this.name = name;
        this.email = email; 
    }

    getName(){

    }

    getId(){

    }

    getEmail(){

    }

    getRole(){

    }

}




//is the below the only thing to export?
module.exports = Employee;