// TODO: Write code to define and export the Employee class

//is a parameter like otherInfo I created going to hold GitHub username (for Engineers), office number (for managers) and School (for interns)?
// Make sure there is no first name/last name issue, there is just a single name accounted for here
// is ID autogenerated? Will find out later but put in the class for now
class Employee {
    constructor (Id, name, jobTitle, email, otherInfo) {
        this.Id = Id;
        this.name = name;
        this.email = email;
        this.otherInfo = otherInfo;
    }

}

//how then to create subclasses in other files?
//do I create a new instance of the class (an object?) in the subclass files and is this where the IDs are assigned i.e.
// const Employee1 = new Employee(1, Jared)

//is the below the only thing to export?
module.exports = Employee