// TODO: Write code to define and export the Employee class

// Make sure there is no first name/last name issue, there is just a single name accounted for here

// is ID Ok being entered as a parameter just like name etc rather than autogenerated or related to role? 

//watch for the capitalization (or not)

class Employee {
    constructor (id, name, email) { 
        this.id = id;
        this.name = name;
        this.email = email; 
    }
    //definitely no reference to Role in the above definition of class, only as a function below?

    getName(){
        return this.name;
    }


    getId(){
        return this.id;
    }

    getEmail(){
        return this.email
    }

    //getRole()—returns 'Employee' - is it right to do this in a function and here?
    getRole(){
        return 'Employee';
    }

}


//temporary code for testing functions
const freshMeat = new Employee(7, "Solomon", "solomon@temple.com");
console.log(freshMeat.getRole());


//is the below the only thing to export?
module.exports = Employee;